create view new_pitch_vw as

with new_pitches as(
	select *, hashbytes('SHA2_256', concat(
				game_key, '|',
				game_date, '|',
				is_Pitch, '|',
				details_type_code, '|',
				pitch_Number, '|',
				details_event, '|',
				details_call_description, '|',
				details_home_Score, '|',
				details_away_Score, '|',
				details_is_In_Play, '|',
				details_is_Strike, '|',
				details_is_Ball, '|',
				count_balls_start, '|',
				count_strikes_start, '|',
				count_outs_start, '|',
				player_id, '|',
				pitch_Data_coordinates_x, '|',
				pitch_Data_coordinates_y, '|',
				result_type, '|',
				result_event, '|',
				result_event_Type, '|',
				result_away_Score, '|',
				result_home_Score, '|',
				about_half_Inning, '|',
				about_inning, '|',
				about_is_Scoring_Play, '|',
				matchup_batter_id, '|' ,
				matchup_pitcher_id, '|',
				matchup_pitchHand_description, '|',
				home_team, '|',
				away_team, '|',
				home_league_name, '|',
				away_league_name, '|',
				batting_team, '|',
				fielding_team, '|',
				pitch_Data_startSpeed, '|',
				pitch_Data_endSpeed, '|',
				pitch_Data_zone, '|',
				pitch_Data_breaks_spin_Rate, '|',
				hit_Data_launch_Speed, '|',
				hit_Data_launch_Angle, '|',
				hit_Data_total_Distance, '|',
				result_is_Out, '|')) as pitch_key
from pitch_stg
where is_Pitch = 1
),

old_pitches as (
	select hashbytes('SHA2_256', concat(
				game_key, '|',
				game_date, '|',
				is_Pitch, '|',
				details_type_code, '|',
				pitch_Number, '|',
				details_event, '|',
				details_call_description, '|',
				details_home_Score, '|',
				details_away_Score, '|',
				details_is_In_Play, '|',
				details_is_Strike, '|',
				details_is_Ball, '|',
				count_balls_start, '|',
				count_strikes_start, '|',
				count_outs_start, '|',
				player_id, '|',
				pitch_Data_coordinates_x, '|',
				pitch_Data_coordinates_y, '|',
				result_type, '|',
				result_event, '|',
				result_event_Type, '|',
				result_away_Score, '|',
				result_home_Score, '|',
				about_half_Inning, '|',
				about_inning, '|',
				about_is_Scoring_Play, '|',
				matchup_batter_id, '|' ,
				matchup_pitcher_id, '|',
				matchup_pitchHand_description, '|',
				home_team, '|',
				away_team, '|',
				home_league_name, '|',
				away_league_name, '|',
				batting_team, '|',
				fielding_team, '|',
				pitch_Data_startSpeed, '|',
				pitch_Data_endSpeed, '|',
				pitch_Data_zone, '|',
				pitch_Data_breaks_spin_Rate, '|',
				hit_Data_launch_Speed, '|',
				hit_Data_launch_Angle, '|',
				hit_Data_total_Distance, '|',
				result_is_Out, '|')) as pitch_key
from pitch_fact
where is_Pitch = 1
)

select distinct game_key,
game_date,
is_Pitch,
details_type_code,
pitch_Number,
details_event,
details_call_description,
details_home_Score,
details_away_Score,
details_is_In_Play,
details_is_Strike,
details_is_Ball,
count_balls_start,
count_strikes_start,
count_outs_start,
player_id,
pitch_Data_coordinates_x,
pitch_Data_coordinates_y,
result_type,
result_event,
result_event_Type,
result_away_Score,
result_home_Score,
about_half_Inning,
about_inning,
about_is_Scoring_Play,
matchup_batter_id,
matchup_pitcher_fullName,
matchup_batter_fullName,
matchup_pitcher_id,
matchup_pitchHand_description,
home_team,
away_team,
home_league_name,
away_league_name,
batting_team,
fielding_team,
pitch_Data_startSpeed,
pitch_Data_endSpeed,
pitch_Data_zone,
pitch_Data_breaks_spin_Rate,
hit_Data_launch_Speed,
hit_Data_launch_Angle,
hit_Data_total_Distance,
result_is_Out
from new_pitches 
where pitch_key not in (select pitch_key from old_pitches)
